export const BASE_PRICE_DEVIATION_PERCENTAGE = 5;
export const MAX_PRICE_POINTS = 10;

export const BASE_MILEAGE_DEVIATION_PERCENTAGE = 10;
export const MAX_MILEAGE_POINTS = 10;

export const SUBSEQUENT_DEVIATION_PERCENTAGE = 1;